import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Provider } from '@/components/ui/provider';
import React from 'react';
import { UserProvider } from '@/contexts/UserContext';
import { cookies } from 'next/headers';
import { getCarousel } from '@/utils/api';
import { CarouselProvider } from '@/contexts/CarouselContext';
import Footer from '@/components/footer/Footer';
import Menu from '@/components/menu/Menu';

export const dynamic = 'force-dynamic';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const userInfoCookie = cookieStore.get('user_info');
    const user = userInfoCookie ? JSON.parse(userInfoCookie.value) : null;

    const initialAlbums = await getCarousel();

    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Provider>
                    <UserProvider initialUser={user}>
                        <CarouselProvider initialAlbums={initialAlbums}>
                            <header>
                                <Menu />
                            </header>
                            {children}
                            <footer>
                                <Footer />
                            </footer>
                        </CarouselProvider>
                    </UserProvider>
                </Provider>
            </body>
        </html>
    );
}
