import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Provider } from '@/components/ui/provider';
import React from 'react';
import { UserProvider } from '@/contexts/UserContext';
import { getCarousel } from '@/utils/api';
import { CarouselProvider } from '@/contexts/CarouselContext';
import Footer from '@/components/footer/Footer';
import { AlbumsProvider } from '@/contexts/AlbumsContext';
import { isLoggedIn } from '@/utils/utils';
import { LibraryProvider } from '@/contexts/LibraryContext';

export const dynamic = 'force-dynamic';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const loggedIn = await isLoggedIn();

    const initialAlbums = await getCarousel();

    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Provider>
                    <UserProvider>
                        <CarouselProvider initialAlbums={initialAlbums}>
                            <LibraryProvider enabled={loggedIn}>
                                <AlbumsProvider enabled={loggedIn}>
                                    {children}
                                </AlbumsProvider>
                            </LibraryProvider>
                            <footer>
                                <Footer />
                            </footer>
                        </CarouselProvider>
                    </UserProvider>
                </Provider>
            </body>
        </html>
    );
}